# Generated by Django 5.2.15 on 2026-06-12 19:18

import django.db.models.deletion
import django.utils.timezone
import marketing.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=180, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='PLANNED', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.team')),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(max_length=180)),
                ('planned_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('currency', models.CharField(default='IRR', max_length=16)),
                ('source_sheet', models.CharField(blank=True, max_length=255)),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_data_json', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='marketing.campaign')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='marketing.team')),
            ],
            options={
                'ordering': ['year', 'month', 'team__name', 'category'],
            },
        ),
        migrations.CreateModel(
            name='UserTeamAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('EDITOR', 'Editor'), ('OBSERVER', 'Observer')], max_length=16)),
                ('can_upload_invoice_files', models.BooleanField(default=False)),
                ('can_upload_payment_proofs', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_view_referral_sms', models.BooleanField(default=False)),
                ('is_global', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='marketing.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'role', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['normalized_name'], name='marketing_v_normali_ae2168_idx')],
                'constraints': [models.UniqueConstraint(fields=('normalized_name',), name='unique_vendor_normalized_name')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=120)),
                ('category', models.CharField(max_length=180)),
                ('cost_bucket', models.CharField(choices=[('TEAM', 'Team'), ('REFERRAL', 'Referral'), ('SMS', 'SMS'), ('GENERAL', 'General')], default='TEAM', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('currency', models.CharField(default='IRR', max_length=16)),
                ('payment_stage', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FINANCE_REVIEW', 'Finance review'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('stage_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('source_sheet', models.CharField(blank=True, max_length=255)),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_data_json', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='marketing.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_invoices', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='marketing.team')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='marketing.vendor')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('INVOICE_IMAGE', 'Invoice image'), ('PAYMENT_PROOF', 'Payment proof'), ('OTHER', 'Other')], max_length=24)),
                ('file', models.FileField(upload_to=marketing.models.invoice_attachment_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='marketing.invoice')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['invoice', 'attachment_type'], name='marketing_i_invoice_5a0249_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_stage', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FINANCE_REVIEW', 'Finance review'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=24)),
                ('new_stage', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FINANCE_REVIEW', 'Finance review'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=24)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='marketing.invoice')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['invoice', '-changed_at'], name='marketing_i_invoice_cb5a13_idx'), models.Index(fields=['new_stage', '-changed_at'], name='marketing_i_new_sta_b17971_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['year', 'name'], name='marketing_c_year_c77d21_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['team', 'year'], name='marketing_c_team_id_a78370_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('name', 'year', 'team'), name='unique_campaign_name_year_team'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['year', 'month'], name='marketing_b_year_047b55_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['team', 'year', 'month'], name='marketing_b_team_id_d26de7_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['category'], name='marketing_b_categor_06429e_idx'),
        ),
        migrations.AddIndex(
            model_name='userteamaccess',
            index=models.Index(fields=['user', 'is_active'], name='marketing_u_user_id_c228d7_idx'),
        ),
        migrations.AddIndex(
            model_name='userteamaccess',
            index=models.Index(fields=['team', 'role'], name='marketing_u_team_id_71877b_idx'),
        ),
        migrations.AddConstraint(
            model_name='userteamaccess',
            constraint=models.CheckConstraint(condition=models.Q(('is_global', True), ('team__isnull', False), _connector='OR'), name='team_required_when_access_is_not_global'),
        ),
        migrations.AddConstraint(
            model_name='userteamaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', False)), fields=('user', 'team', 'role'), name='unique_team_role_access_per_user'),
        ),
        migrations.AddConstraint(
            model_name='userteamaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', True)), fields=('user', 'role'), name='unique_global_role_access_per_user'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='marketing_i_invoice_823a93_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['vendor', 'invoice_number'], name='marketing_i_vendor__3e7ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['team', 'invoice_date'], name='marketing_i_team_id_6263d0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['cost_bucket', 'invoice_date'], name='marketing_i_cost_bu_b9da2e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_stage'], name='marketing_i_payment_4b2ae5_idx'),
        ),
    ]
