# Generated by Django 5.2.15 on 2026-06-13 00:29

import re
import unicodedata

import django.db.models.deletion
from django.db import migrations, models


ALIASES = [
    (
        "Operation & Analysis",
        "Ops & Analytics",
        "Seeded from workbook discovery: same team name written two ways.",
    ),
    (
        "Brand (PR & Social & CSR)",
        "Brand",
        "Seeded from follow-up voice feedback: Brand sub-label should roll into Brand.",
    ),
]


def normalize_name(value: str) -> str:
    text = unicodedata.normalize("NFKC", value or "")
    text = text.replace("ي", "ی").replace("ك", "ک")
    text = re.sub(r"[^\w\sآ-ی]", " ", text, flags=re.UNICODE)
    return re.sub(r"\s+", " ", text).strip().casefold()


def seed_team_aliases(apps, schema_editor):
    Team = apps.get_model("marketing", "Team")
    TeamAlias = apps.get_model("marketing", "TeamAlias")
    Invoice = apps.get_model("marketing", "Invoice")
    BudgetLine = apps.get_model("marketing", "BudgetLine")
    Campaign = apps.get_model("marketing", "Campaign")
    UserTeamAccess = apps.get_model("marketing", "UserTeamAccess")

    for raw_name, canonical_name, notes in ALIASES:
        canonical = Team.objects.filter(name=canonical_name).first()
        alias_team = Team.objects.filter(name=raw_name).first()
        if canonical is None:
            continue

        TeamAlias.objects.update_or_create(
            raw_name=raw_name,
            defaults={
                "normalized_raw_name": normalize_name(raw_name),
                "team": canonical,
                "is_active": True,
                "notes": notes,
            },
        )

        if alias_team is None or alias_team.pk == canonical.pk:
            continue

        for campaign in Campaign.objects.filter(team=alias_team):
            existing = Campaign.objects.filter(
                name=campaign.name,
                year=campaign.year,
                team=canonical,
            ).exclude(pk=campaign.pk).first()
            if existing:
                Invoice.objects.filter(campaign=campaign).update(campaign=existing)
                BudgetLine.objects.filter(campaign=campaign).update(campaign=existing)
                campaign.delete()
            else:
                campaign.team = canonical
                campaign.save(update_fields=["team"])

        Invoice.objects.filter(team=alias_team).update(team=canonical)
        BudgetLine.objects.filter(team=alias_team).update(team=canonical)

        for access in UserTeamAccess.objects.filter(team=alias_team, is_global=False):
            existing = UserTeamAccess.objects.filter(
                user=access.user,
                team=canonical,
                role=access.role,
                is_global=False,
            ).exclude(pk=access.pk).first()
            if existing:
                existing.can_upload_invoice_files = (
                    existing.can_upload_invoice_files or access.can_upload_invoice_files
                )
                existing.can_upload_payment_proofs = (
                    existing.can_upload_payment_proofs or access.can_upload_payment_proofs
                )
                existing.can_export = existing.can_export or access.can_export
                existing.can_view_referral_sms = existing.can_view_referral_sms or access.can_view_referral_sms
                existing.is_active = existing.is_active or access.is_active
                existing.save(
                    update_fields=[
                        "can_upload_invoice_files",
                        "can_upload_payment_proofs",
                        "can_export",
                        "can_view_referral_sms",
                        "is_active",
                    ]
                )
                access.delete()
            else:
                access.team = canonical
                access.save(update_fields=["team"])

        alias_team.is_active = False
        alias_team.save(update_fields=["is_active"])


def unseed_team_aliases(apps, schema_editor):
    TeamAlias = apps.get_model("marketing", "TeamAlias")
    TeamAlias.objects.filter(raw_name__in=[raw_name for raw_name, _canonical, _notes in ALIASES]).update(
        is_active=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_name', models.CharField(max_length=160, unique=True)),
                ('normalized_raw_name', models.CharField(db_index=True, max_length=180, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='marketing.team')),
            ],
            options={
                'verbose_name_plural': 'team aliases',
                'ordering': ['raw_name'],
                'indexes': [models.Index(fields=['normalized_raw_name', 'is_active'], name='marketing_t_normali_d8ab6c_idx')],
            },
        ),
        migrations.RunPython(seed_team_aliases, unseed_team_aliases),
    ]
