# Generated by Django 5.2 on 2026-06-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_canonical_campaign_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpendCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("source_sheet", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "spend categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Requester",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("source_sheet", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubTeam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("source_sheet", models.CharField(blank=True, max_length=255)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_teams",
                        to="marketing.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "sub team",
                "verbose_name_plural": "sub teams",
                "ordering": ["name"],
            },
        ),
    ]
