# Generated by Django 5.2.15 on 2026-06-13 16:56

import django.db.models.deletion
import django.utils.timezone
import marketing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_reference_lookup_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('contract_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('stage', models.CharField(choices=[('DRAFT', 'Draft'), ('INTERNAL_LEGAL_REVIEW', 'Internal legal review'), ('SENT_TO_COUNTERPARTY', 'Sent to counterparty'), ('COUNTERPARTY_REVIEW', 'Counterparty legal review'), ('NEGOTIATION', 'Negotiation / revisions'), ('PENDING_SIGNATURE', 'Pending signature'), ('SIGNED', 'Signed / active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32)),
                ('stage_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('signed_at', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('currency', models.CharField(default='IRR', max_length=16)),
                ('counterparty_contact', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='marketing.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contracts', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='marketing.vendor')),
            ],
            options={
                'ordering': ['end_date', 'vendor__name'],
            },
        ),
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('DRAFT_VERSION', 'Draft version'), ('FINAL_VERSION', 'Final signed version'), ('OTHER', 'Other document')], max_length=24)),
                ('file', models.FileField(upload_to=marketing.models.contract_attachment_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='marketing.contract')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_stage', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('INTERNAL_LEGAL_REVIEW', 'Internal legal review'), ('SENT_TO_COUNTERPARTY', 'Sent to counterparty'), ('COUNTERPARTY_REVIEW', 'Counterparty legal review'), ('NEGOTIATION', 'Negotiation / revisions'), ('PENDING_SIGNATURE', 'Pending signature'), ('SIGNED', 'Signed / active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], max_length=32)),
                ('new_stage', models.CharField(choices=[('DRAFT', 'Draft'), ('INTERNAL_LEGAL_REVIEW', 'Internal legal review'), ('SENT_TO_COUNTERPARTY', 'Sent to counterparty'), ('COUNTERPARTY_REVIEW', 'Counterparty legal review'), ('NEGOTIATION', 'Negotiation / revisions'), ('PENDING_SIGNATURE', 'Pending signature'), ('SIGNED', 'Signed / active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], max_length=32)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='marketing.contract')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['stage'], name='marketing_c_stage_c82e18_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['team', 'stage'], name='marketing_c_team_id_1cd22a_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['vendor', 'stage'], name='marketing_c_vendor__142747_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['end_date'], name='marketing_c_end_dat_74638e_idx'),
        ),
        migrations.AddIndex(
            model_name='contractattachment',
            index=models.Index(fields=['contract', 'attachment_type'], name='marketing_c_contrac_b9435e_idx'),
        ),
        migrations.AddIndex(
            model_name='contractstatushistory',
            index=models.Index(fields=['contract', '-changed_at'], name='marketing_c_contrac_c891c5_idx'),
        ),
        migrations.AddIndex(
            model_name='contractstatushistory',
            index=models.Index(fields=['new_stage', '-changed_at'], name='marketing_c_new_sta_4fd6df_idx'),
        ),
    ]
