# Generated by Django 5.2.15 on 2026-06-13 17:09

from django.db import migrations, models
from django.db.models import Count, Max


def dedupe_budget_lines(apps, schema_editor):
    """Collapse duplicate imported budget lines before enforcing the uniqueness constraint.

    Earlier imports could create more than one BudgetLine for the same workbook source row + month
    (e.g. after a team alias merge changed the resolved team). Keep the most recently created row
    in each group and delete the rest so totals stop being inflated.
    """
    BudgetLine = apps.get_model("marketing", "BudgetLine")
    duplicate_groups = (
        BudgetLine.objects.filter(source_row_number__isnull=False)
        .values("source_sheet", "source_row_number", "year", "month")
        .annotate(row_count=Count("id"), keep_id=Max("id"))
        .filter(row_count__gt=1)
    )
    for group in duplicate_groups:
        BudgetLine.objects.filter(
            source_sheet=group["source_sheet"],
            source_row_number=group["source_row_number"],
            year=group["year"],
            month=group["month"],
        ).exclude(id=group["keep_id"]).delete()


def noop_reverse(apps, schema_editor):
    # Deleted duplicate rows cannot be reconstructed; re-running the importer restores correct data.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_contract_contractattachment_contractstatushistory_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_budget_lines, noop_reverse),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(condition=models.Q(('source_row_number__isnull', False)), fields=('source_sheet', 'source_row_number', 'year', 'month'), name='unique_budget_line_source_row_month'),
        ),
    ]
