# Generated by Django 5.2.15 on 2026-06-15 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_anonymize_business_section_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('source_row_number__isnull', False)), fields=('source_sheet', 'source_row_number', 'vendor', 'invoice_number'), name='unique_invoice_source_row_vendor_number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('source_row_number__isnull', True)), fields=('invoice_number', 'vendor'), name='unique_manual_invoice_number_vendor'),
        ),
    ]
