# Generated by Django 5.2.15 on 2026-06-16 21:45

from django.db import migrations, models


def _seed_reference_and_backfill(apps, schema_editor):
    from decimal import Decimal

    BusinessLine = apps.get_model("marketing", "BusinessLine")
    InsuranceRateOption = apps.get_model("marketing", "InsuranceRateOption")
    Invoice = apps.get_model("marketing", "Invoice")

    def norm(value: str) -> str:
        return (value or "").strip().casefold()

    for name in ("Retail", "Junior", "Business"):
        BusinessLine.objects.get_or_create(
            normalized_name=norm(name),
            defaults={"name": name},
        )

    for percent, label in (
        (Decimal("16.67"), "Standard withholding"),
        (Decimal("7.78"), "Reduced withholding"),
    ):
        InsuranceRateOption.objects.get_or_create(percent=percent, defaults={"label": label})

    for invoice in Invoice.objects.all().iterator():
        section = (getattr(invoice, "business_section", "") or "").strip()
        if section:
            BusinessLine.objects.get_or_create(
                normalized_name=norm(section),
                defaults={"name": section},
            )
        if invoice.action_cost_amount is None and invoice.amount is not None:
            total = Decimal(invoice.amount)
            action = (total * Decimal("10") / Decimal("110")).quantize(Decimal("1"))
            tax = total - action
            invoice.action_cost_amount = action
            invoice.tax_amount = tax
            invoice.paid_amount = total
            invoice.save(update_fields=["action_cost_amount", "tax_amount", "paid_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_invoice_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'business line',
                'verbose_name_plural': 'business lines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceRateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=6, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['percent'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='action_cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base marketing action cost before VAT (X in voice notes).', max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='insurance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='insurance_rate_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount finance pays after insurance withholding.', max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
        migrations.RunPython(_seed_reference_and_backfill, migrations.RunPython.noop),
    ]
