# Generated by Django 5.2.15 on 2026-06-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0013_remove_placeholder_business_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='business_section',
            field=models.CharField(blank=True, db_index=True, help_text='Business segment from Excel Business Section (e.g. Retail, Junior, Business).', max_length=120),
        ),
    ]
